# Generated by Django 5.0.1 on 2024-01-17 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='наименование продукта')),
                ('model', models.CharField(max_length=250, verbose_name='модель продукта')),
                ('product_launch_date', models.DateField(verbose_name='дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='наименование звена сети')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='адрес электронной почты')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='страна')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='город')),
                ('treet', models.CharField(blank=True, max_length=100, null=True, verbose_name='улица')),
                ('house', models.PositiveIntegerField(blank=True, null=True, verbose_name='номер дома')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='задолженость перед поставщиком')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время и дата создания')),
                ('net', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider', to='net.net', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'звено сети',
                'verbose_name_plural': 'звенья сети',
            },
        ),
    ]
